name: Build Python Executable ğŸš€

on:
  release:
    types:
      - edited
      - released

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code ğŸ“¥
        uses: actions/checkout@v4

      - id: get_version
        uses: jannemattila/get-version-from-tag@v3

      - name: Set up Python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Python dependencies ğŸ’¾
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies âš™ï¸
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pyinstaller
          python -m pip install --no-cache-dir -r requirements.txt

      - name: Verify PyInstaller installation âœ…
        run: python -m PyInstaller --version

      - name: Build executable ğŸ› ï¸
        run: |
          python -m PyInstaller --onefile --log-level=DEBUG src/main.py --name=Load-Tester_v${{ steps.get_version.outputs.version }}

      - name: Upload Executable ğŸ“¤
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Load-Tester_v${{ steps.get_version.outputs.version }}.exe
